export const ShoppingBagActionTypes = {
  TOGGLE_BAG_HIDDEN: "TOGGLE_BAG_HIDDEN",
  TOOGLE_BAG_TRUE: "TOOGLE_BAG_TRUE",
  ADD_ITEM: "ADD_ITEM",
  SUBTRACT_ITEM: "SUBTRACT_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
};
